name: Update README
on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:
jobs:
  build:
    name: Update this repo's README with recent activity
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: sosososoyoen/sosososoyoen@main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
